### ISSUE TITLE
有兴趣 增加 C#的兼容支持么？

### ISSUE THREAD

**Issue by sgf** [wq19901103wq/troy#1]
感觉 似乎很不错。我看了很多C++库。要么需要 写 序列化定义（就是序列化的先后顺序）。
要么就是要写各种 中间定义文件。
只有这个库 让人眼前一亮。

**Comment by wq19901103wq** [comment]
目前没有时间...troy只是一个框架性的东西，了解序列化具体的算法直接继承base应该就可以直接实现...

**Comment by sgf** [comment]
ok,了解
当然其实主要是C++ 的序列化这块。
我一直觉得C++ 这块不能够彻底解决  对象的无入侵式的序列化。好的我看看实现。

**Comment by wq19901103wq** [comment]
代码很简单 核心代码就100行 主要是利用了struct binding 可聚合的判断 boost预处理器以及大量的编译器编程技巧。有问题随时问我.
